### ISSUE TITLE
How to predict next value

### ISSUE THREAD

**Issue by styphoiz** [TimeSerieser/How-to-Guess-Accurately-3-Lottery-Numbers-Out-of-6-using-LSTM#1]
Hi

I've read your post however what I am not understanding is how do you then calculate the next draw based of the data, currently when you read it a second time of the last 7 records, you get back the same results as the previous run.

**Comment by styphoiz** [comment]
Please ignore, I see I had a coding issue

**Comment by fab-kbh** [comment]
hi there @styphoiz ,
were you able to solve this problem?

**Comment by styphoiz** [comment]
@fab-kbh yeah I did, the problem here is that the training dataset is able to predict the next number in the sequence because it is part of the training so it shows the number usually correct or off by one number, when it has to actually try and predict the next set of numbers after that or if you exclude the last set of numbers and try to get it to predict those, it gets it wrong.
Unless there's an actual sequence that the model can identify, it wouldn't work.
